### ISSUE TITLE
[Feat] - Add bitwarden docker

### ISSUE THREAD

**Issue by jenaye** [CMEPW/Smersh#24]
https://bitwarden.com/help/api/

can you handle this please @SilouFr  ? :) 

the goal its to add it into docker-compose and after  i'll update API to force url instead of string

**Comment by jenaye** [comment]
something like : 

```
  bitwarden:
    image: bitwardenrs/server:latest
    ports:
      - target: 80
        published: 8888
        protocol: tcp
    volumes:
      - ./data/bitwarden:/data
    restart: on-failure
 ```
    
    
![image](https://user-images.githubusercontent.com/15458329/108442519-7aa09e80-7257-11eb-951d-a05c1ec6e283.png)
